language: csharp
mono: none
dotnet: 3.1.202
sudo: required
addons:
  apt:
    packages:
    - dotnet-sdk-3.0

before_install:
  - sudo apt-get install nuget

branches:
    only:
     - Testing

script:
 - dotnet build
 - dotnet test TestCore/TestCore.csproj"
