language: csharp
mono: none
dotnet: 3.1.202
sudo: required

before_install:
  - sudo apt-get install nuget
install:
  - dotnet restore
branches:
    only:
     - Testing

script:
 - dotnet build
 - dotnet test TestCore/TestCore.csproj"