language: csharp
mono: none
dotnet: 3.1.202
sudo: required
addons:
  apt:
    packages:
    - dotnet-sdk-3.0 
deploy:
  provider: gae
  project: resolute-land-274909
  keyfile: credentials.tar.gz
  
before_install:
 - openssl aes-256-cbc -K $encrypted_d80a2d296111_key -iv $encrypted_d80a2d296111_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
 
install:
   - dotnet restore OnlineRetailer.sln

script:
 - dotnet build OnlineRetailer.sln
 - dotnet test TestCore/TestCore.csproj