language: csharp
mono: none
dotnet: 3.1.202
sudo: required
addons:
  apt:
    packages:
    - dotnet-sdk-3.0

before_install:
  - sudo apt-get install nuget
install:
   - dotnet restore OnlineRetailer.sln

branches:
    only:
     - Messaging

script:
 - dotnet build OnlineRetailer.sln
 - dotnet test TestCore/TestCore.csproj