os: windows
language: csharp
mono: none
sudo: required

before_install:
  - sudo apt-get install nuget
branches:
    only:
     - Testing

script:
- choco install dotnetcore-sdk
- dotnet --version
- dotnet restore
- dotnet build
- dotnet test TestCore/TestCore.csproj"