language: csharp
mono: none
dotnet: 3.1.202
sudo: required
addons:
  apt:
    packages:
    - dotnet-sdk-3.0 
 
install:
   - dotnet restore OnlineRetailer.sln

script:
 - dotnet build OnlineRetailer.sln
 - dotnet test TestCore/TestCore.csproj