language: csharp
mono: none
dotnet: 3.1.202
sudo: required
addons:
  apt:
    packages:
    - dotnet-sdk-3.0

before_install:
  - openssl aes-256-cbc -K $encrypted_a3c2492b5906_key -iv $encrypted_a3c2492b5906_iv -in gce.json.enc -out gce.json -d
install:
   - dotnet restore OnlineRetailer.sln

script:
 - dotnet build OnlineRetailer.sln
 - dotnet test TestCore/TestCore.csproj

 deploy:
  provider: gae
  project: resolute-land-274909
  keyfile: gce.json
  on:
    all_branches: true