language: csharp
solution: OnlineRetailer.sln

install:
  - nuget restore OnlineRetailer.sln
  - nuget install xunit.runners -Version 2.4.1 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release OnlineRetailer.sln
  - mono ./testrunner/xunit.runners.2.4.1/tools/xunit.console.clr4.exe ./OnlineRetailer_Partial/TestCore/bin/Debug/netcoreapp3.1/TestCore.dll