apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi
        image: gcr.io/resolute-land-274909/github.com/nagydominik/onlineretailer_partial/customerapi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: customerapi-config
              key: ASPNETCORE_ENVIRONMENT      
        - name: CloudAMQP
          valueFrom:
            configMapKeyRef:
              name: customerapi-config
              key: CloudAMQP
        - name: SQLServer
          valueFrom:
            configMapKeyRef:
              name: customerapi-config
              key: SQLServer
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: customerapi
  ports:
  - port: 80
    nodePort: 31003