apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi
        image: nagydominik98/or_customerapi:release
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: customerapi-config
              key: ASPNETCORE_ENVIRONMENT      
        - name: CloudAMQP
          valueFrom:
            configMapKeyRef:
              name: customerapi-config
              key: CloudAMQP
        - name: SQLServer
          valueFrom:
            configMapKeyRef:
              name: customerapi-config
              key: SQLServer
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: customerapi
  ports:
  - port: 80
    nodePort: 31003
---
apiVersion: v1
kind: ConfigMap
data:
  ASPNETCORE_ENVIRONMENT: ""
  CloudAMQP: ""
  SQLServer: ""
metadata:
  labels:
    app: customerapi
  name: customerapi-config
  namespace: default
