apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: gcr.io/resolute-land-274909/github.com/nagydominik/onlineretailer_partial/orderapi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: orderapi-config
              key: ASPNETCORE_ENVIRONMENT      
        - name: CloudAMQP
          valueFrom:
            configMapKeyRef:
              name: orderapi-config
              key: CloudAMQP
        - name: SQLServer
          valueFrom:
            configMapKeyRef:
              name: orderapi-config
              key: SQLServer
---
apiVersion: v1
kind: Service
metadata:
  name: orderapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: orderapi
  ports:
  - port: 80
    nodePort: 31002