apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - name: productapi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: productapi-config
              key: ASPNETCORE_ENVIRONMENT      
        - name: CloudAMQP
          valueFrom:
            configMapKeyRef:
              name: productapi-config
              key: CloudAMQP
        - name: SQLServer
          valueFrom:
            configMapKeyRef:
              name: productapi-config
              key: SQLServer
---
apiVersion: v1
kind: Service
metadata:
  name: productapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: productapi
  ports:
  - port: 80
    nodePort: 31001
---
apiVersion: v1
kind: ConfigMap
data:
  ASPNETCORE_ENVIRONMENT: ""
  CloudAMQP: ""
  SQLServer: ""
metadata:
  labels:
    app: productapi
  name: productapi-config
  namespace: default