apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - name: productapi
        image: gcr.io/resolute-land-274909/github.com/nagydominik/onlineretailer_partial
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: productapi-config
              key: ASPNETCORE_ENVIRONMENT      
        - name: CloudAMQP
          valueFrom:
            configMapKeyRef:
              name: productapi-config
              key: CloudAMQP
        - name: SQLServer
          valueFrom:
            configMapKeyRef:
              name: productapi-config
              key: SQLServer
---
apiVersion: v1
kind: Service
metadata:
  name: productapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: productapi
  ports:
  - port: 80
    nodePort: 31001